version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:20  # On peut utiliser node ou hugo directement via apt
    steps:
      - checkout

      - run:
          name: Installer Hugo
          command: |
            sudo apt-get update
            sudo apt-get install -y hugo

      - run:
          name: Générer le site
          command: hugo

      - run:
          name: Déployer sur GitHub Pages
          command: |
            git config --global user.name "romaincode99"
            git config --global user.email "romain.lemore.99@gmail.com"
            git clone --branch gh-pages https://github.com/romaincode99/myWebSite out
            rm -rf out/*
            cp -r public/* out/
            cd out
            git add .
            git commit -m "Déploiement automatique via CircleCI"
            git push origin gh-pages

workflows:
  version: 2
  build-deploy:
    jobs:
      - build

